Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/precise32"
  
    config.vm.define "sgc" do |sgc|
  
        sgc.vm.hostname = "sgc.home"
  
        sgc.vm.network :forwarded_port, host: 8083, guest: 80
        sgc.vm.network :forwarded_port, host: 3307, guest: 3306
        sgc.vm.provision :shell, path: "bootstrap.sh"
        
  end

end